#!/usr/bin/python

import sys

import gobject

from sugar.activity import Activity
from sugar.LogWriter import LogWriter
from sugar import theme

theme.setup()

lw = LogWriter(sys.argv[1])
lw.start()

if len(sys.argv) == 4:
	Activity.register_factory(sys.argv[1], sys.argv[2], sys.argv[3])
else:
	Activity.register_factory(sys.argv[1], sys.argv[2])
