#!/usr/bin/python

import sys
import logging

import pygtk
pygtk.require('2.0')
import gobject
import gtk
import dbus.glib

# Work around for dbus mutex locking issue
gtk.gdk.threads_init()
dbus.glib.threads_init()

from sugar.activity import ActivityFactory
from sugar.LogWriter import LogWriter
from sugar import theme

logging.info('Starting activity factory %s' % sys.argv[1])

theme.setup()

#lw = LogWriter(sys.argv[1])
#lw.start()

if len(sys.argv) == 4:
	ActivityFactory.register_factory(sys.argv[1], sys.argv[2], sys.argv[3])
else:
	ActivityFactory.register_factory(sys.argv[1], sys.argv[2])

gtk.main()
