#!/usr/bin/python

import logging
from PresenceService import PresenceService
import sugar.logger

#sugar.logger.start('PresenceService')

logging.info('Starting presence service')

PresenceService.main()
