#!/usr/bin/python

# Copyright (C) 2006, Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import sys
import os

import pygtk
pygtk.require('2.0')

curdir = os.path.abspath(os.path.dirname(__file__))
sourcedir = os.path.dirname(curdir)

if os.path.isfile(os.path.join(sourcedir, 'sugar/__uninstalled__.py')):
	print 'Running sugar from ' + sourcedir + ' ...'
	sys.path.insert(0, sourcedir)
else:
	print 'Running the installed sugar...'

from sugar import env

env.setup_system()

from sugar.session.Emulator import Emulator

if os.environ.has_key('SUGAR_EMULATOR') and \
   os.environ['SUGAR_EMULATOR'] == 'yes':
	emulator = Emulator()
	emulator.start()

from Session import Session

session = Session()
session.start()
