#!/usr/bin/python
import sys

import dbus
import dbus.glib

bus = dbus.SessionBus()
proxy_obj = bus.get_object('com.redhat.Sugar.Shell', '/com/redhat/Sugar/Shell')
shell = dbus.Interface(proxy_obj, 'com.redhat.Sugar.Shell')

if sys.argv[1] == 'in':
	shell.zoom_in()
elif sys.argv[1] == 'out':
	shell.zoom_out()
