#!/usr/bin/python
import sys
import logging

import pygtk
pygtk.require('2.0')
import gtk
import dbus.glib

# Work around for dbus mutex locking issue
gtk.gdk.threads_init()
dbus.glib.threads_init()

from sugar.activity import ActivityFactory

logging.info('Starting activity factory %s' % sys.argv[1])

ActivityFactory.register_factory(sys.argv[1], sys.argv[2])

gtk.main()
