#!/usr/bin/python

# Copyright (C) 2006, Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import sys
import os

import pygtk
pygtk.require('2.0')
import gtk

from sugar import logger
from sugar import profile
from sugar import env
from sugar import TracebackUtils

logger.cleanup()
logger.start('shell')

sys.path.insert(0, os.path.join(env.get_data_dir(), 'shell'))

from view.FirstTimeDialog import FirstTimeDialog
from view.Shell import Shell
from model.ShellModel import ShellModel

name = profile.get_nick_name() 
if not name or not len(name):
	dialog = FirstTimeDialog()
	dialog.run()
	profile.update()

model = ShellModel()
shell = Shell(model)

tbh = TracebackUtils.TracebackHelper()
try:
	gtk.main()
except KeyboardInterrupt:
	print 'Ctrl+C pressed, exiting...'
del tbh
