sugardir = $(pythondir)/jarabe/journal
sugar_PYTHON =				\
	__init__.py			\
	basejournalview.py		\
	bundlelauncher.py		\
	detailview.py			\
	expandedentry.py		\
	gridview.py			\
	iconview.py			\
	iconmodel.py			\
	journalactivity.py		\
	journalentrybundle.py		\
	journaltoolbox.py		\
	journalwindow.py		\
	keepicon.py			\
	listmodel.py			\
	listview.py			\
	misc.py				\
	modalalert.py			\
	model.py			\
	objectchooser.py		\
	projectview.py			\
	timeline.py			\
	palettes.py			\
	joglyph.py			\
	momentcard.py			\
	reflectguard.py			\
	reflection.py			\
	reflectstyle.py			\
	volumestoolbar.py
