#!/usr/bin/python

import sys

# FIXME Without args we should startup the session thing
if len(sys.argv) == 1 or sys.argv[1] == 'shell':
	import sugar.shell
	sugar.shell.main()
elif sys.argv[1] == 'chat':
	import sugar.chat
	sugar.chat.main()
elif sys.argv[1] == 'browser':
	import sugar.browser
	sugar.browser.main()
else:
	print "Unkown activity"
