#!/usr/bin/python

# Copyright (C) 2006, Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import os

import gobject

from sugar.presence import PresenceService

PresenceService.start()

base_path = os.path.abspath(os.path.dirname(__file__))

stage_path = os.path.join(base_path, 'demo')
for bot_file in os.listdir(stage_path):
	if bot_file.endswith('.py'):
		execfile(os.path.join(stage_path, bot_file))

mainloop = gobject.MainLoop()
mainloop.run()
