#!/usr/bin/python
import os

import gobject

from sugar.session.TestSession import TestSession
from sugar.presence import PresenceService

session = TestSession()
session.start()

PresenceService.start()

base_path = os.path.abspath(os.path.dirname(__file__))

stage_path = os.path.join(base_path, 'demo')
for bot_file in os.listdir(stage_path):
	if bot_file.endswith('.py'):
		execfile(os.path.join(stage_path, bot_file))

mainloop = gobject.MainLoop()
mainloop.run()
