#!/usr/bin/env python
# vi: ts=4 ai noet 
#
# Copyright (C) 2006, Red Hat, Inc.
# Copyright (C) 2007, One Laptop Per Child
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import sys
import os
import logging

from sugar import logger
logger.start('shellservice')

import gobject
import dbus.glib
 
from sugar import env

sys.path.append(env.get_service_path('shell'))

import clipboardservice
import objecttypeservice
import activityregistryservice

logging.info('Starting shell service.')

gobject.threads_init()
dbus.glib.threads_init()

clipboard_service = clipboardservice.get_instance()
object_type_registry = objecttypeservice.get_instance()
activity_registry = activityregistryservice.get_instance()

loop = gobject.MainLoop()
try:
    loop.run()
except KeyboardInterrupt:
    print 'Ctrl+C pressed, exiting...'

