#!/usr/bin/python
import logging
import sys
import os

from sugar import logger
from sugar import env

sys.path.insert(0, env.get_services_dir())

from presence import PresenceService

logger.start('presenceservice')

logging.info('Starting presence service')

PresenceService.main()
