#!/usr/bin/env python
# vi: ts=4 ai noet 
#
# Copyright (C) 2006, Red Hat, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA

import logging
import sys
import os

from sugar import logger
from sugar import env

sys.path.append(env.get_service_path('presence'))

test=0
if len(sys.argv) > 1:
    try:
        test = int(sys.argv[1])
    except ValueError:
        logging.debug("Bad test user number.")
    if test < 1 or test > 10:
        logging.debug("Bad test user number.")

if test > 0:
    logger.start('test-%d-presenceservice' % test)
else:
    logger.start('presenceservice')

import presenceservice

logging.info('Starting presence service')

presenceservice.main(test)
