# Copyright (C) 2026 Sugar Labs
#
# SPDX-License-Identifier: GPL-3.0-or-later

import json

from jarabe.model.aodrag import get_api_reference


def build_system_prompt(spec, references=()):
    learning_direction = _CATEGORY_BLOCKS.get(
        spec.category, _CATEGORY_BLOCKS['creation'])
    if spec.template != 'auto':
        learning_direction = '%s\n%s' % (
            learning_direction,
            _TEMPLATE_HINTS.get(spec.template, ''),
        )
    reference_text = _format_references(references)
    return (
        'You are Sugar Activity on Demand, a planner for safe, '
        'learner-friendly Sugar activities that will be generated by an '
        'LLM code generator.\n\n'
        'PRIORITY RULES\n'
        '1. Return one JSON object and no Markdown.\n'
        '2. Plan for Sugar Activity and GTK3, not Gtk.Application.\n'
        '3. Design the actual activity the learner asked for. Do not force '
        'the idea into a canned quiz/canvas/grid unless that is truly the '
        'best design.\n'
        '4. Retrieved references are API and pattern examples, not templates '
        'to copy. Use them to understand how Sugar activities are structured, '
        'how the toolbar/canvas lifecycle works, and how Journal persistence '
        'is wired.\n'
        '5. The provider code generator owns the activity.py source for '
        'provider jobs. Do not plan a local-template substitute.\n'
        '6. Do not request network access, subprocesses, or unrestricted '
        'filesystem access.\n'
        '7. The RAG step has already supplied the relevant Sugar examples. '
        'Do not ask for more ingestion, training, uploads, or setup.\n'
        '8. If the learner request contains a current activity.py excerpt, '
        'treat it as an iterative refinement: preserve the working activity '
        'and change only what the refinement asks for.\n'
        '9. Respect the selected category, age band, and license.\n\n'
        '%s\n\n'
        'SELECTED LEARNING DIRECTION\n%s\n\n'
        'RETRIEVED SUGAR REFERENCES\n%s\n\n'
        'Return these JSON fields:\n'
        '- name: short activity name\n'
        '- template: closest reference family: canvas, carrom, chess, grid, '
        'narrative, quiz, or utility\n'
        '- activity_kind: the specific kind of activity to build, in your '
        'own words\n'
        '- summary: one sentence\n'
        '- learner_goal: one observable learner goal\n'
        '- learner_steps: 3 to 5 short steps\n'
        '- interaction_model: how learners interact with the activity\n'
        '- ui_regions: 3 to 6 visible interface regions or controls\n'
        '- state_schema: short description of the data saved to the Journal\n'
        '- word_bank: up to 8 useful words\n'
        '- features: optional list of activity features teachers can inspect\n'
        '- classroom_flow: optional 3 to 5 step classroom use flow\n'
        '- teacher_notes: optional short facilitation notes\n'
        '- assessment_prompts: optional reflection/check-for-understanding '
        'prompts\n'
        '- materials: optional short list of classroom materials\n'
        '- refinement_notes: optional list of changes to preserve or apply '
        'when this is a refinement\n'
        '- chess_show_move_log: optional boolean for chess activities; false '
        'means use a clean board without a move-history panel\n'
        '- questions: optional list of question/answer objects for quizzes\n'
        '- starter_text: optional opening text for narrative activities\n'
    ) % (
        get_api_reference(),
        learning_direction,
        reference_text or 'No external examples were retrieved.',
    )


def build_user_prompt(spec):
    return (
        'Plan a bespoke Sugar activity from this structured learner request. '
        'Use the retrieved Sugar references as context for how real Sugar '
        'activities are built, then make the plan specific enough that a '
        'second model call can generate a complete activity.py. Do not fall '
        'back to canned templates, placeholders, or generic demos:\n\n%s'
        % spec.to_prompt()
    )


def extract_json_object(text):
    if not isinstance(text, str):
        raise ValueError('Provider response must be text.')

    candidate = text.strip()
    if candidate.startswith('```'):
        first_newline = candidate.find('\n')
        last_fence = candidate.rfind('```')
        if first_newline >= 0 and last_fence > first_newline:
            candidate = candidate[first_newline + 1:last_fence].strip()

    try:
        value = json.loads(candidate)
    except json.JSONDecodeError:
        start = candidate.find('{')
        end = candidate.rfind('}')
        if start < 0 or end <= start:
            raise ValueError('Provider response did not contain JSON.')
        try:
            value = json.loads(candidate[start:end + 1])
        except json.JSONDecodeError as error:
            raise ValueError('Provider returned invalid JSON: %s' % error)

    if not isinstance(value, dict):
        raise ValueError('Provider JSON must be an object.')
    return value


def _format_references(references):
    blocks = []
    for index, document in enumerate(references[:5], 1):
        text = ' '.join(document.text.split())
        blocks.append(
            'Reference %d - %s:\n%s' % (index, document.title, text[:1800])
        )
    return '\n\n'.join(blocks)


_CATEGORY_BLOCKS = {
    'logic_math': (
        'Favor patterns, reasoning, explanation, immediate feedback, and '
        'multiple ways to reach or describe an answer.'
    ),
    'science': (
        'Favor observing, predicting, experimenting, measuring, and '
        'comparing results, with simple simulations or data the learner '
        'can change and re-run.'
    ),
    'language': (
        'Favor reading, writing, vocabulary, storytelling, and word play, '
        'with feedback that celebrates expression and revision.'
    ),
    'tools_utils': (
        'Favor a focused tool that helps learners measure, organize, count, '
        'compare, or investigate something meaningful.'
    ),
    'games': (
        'Favor a clear play loop, visible goals, understandable state, and '
        'feedback that supports experimentation instead of punishment.'
    ),
    'creation': (
        'Favor drawing, writing, composing, building, and learner-owned '
        'artifacts that can be revised and shared.'
    ),
}

_TEMPLATE_HINTS = {
    'canvas': (
        'If a canvas is appropriate, use direct manipulation and a clear/reset '
        'action.'
    ),
    'carrom': (
        'If carrom is appropriate, use a square board, corner pockets, coins, '
        'a striker/aim marker, two-player turns, scoring, fouls, and Journal '
        'persistence.'
    ),
    'chess': (
        'If chess is appropriate, use an 8x8 board, turns, pieces, move '
        'feedback, and Journal persistence.'
    ),
    'grid': (
        'If a grid is appropriate, use visible state, patterns, and '
        'reversible choices.'
    ),
    'narrative': (
        'If writing is appropriate, use a large editable area and a useful '
        'starter.'
    ),
    'quiz': (
        'If a quiz is appropriate, use learner-friendly questions and '
        'feedback.'
    ),
    'utility': (
        'If a utility is appropriate, use visible input and immediate output.'
    ),
}
