#!/usr/bin/python

import sys
import os

curdir = os.path.dirname(__file__)

def append_to_python_path(path):
	if os.environ.has_key('PYTHONPATH'):
		os.environ['PYTHONPATH'] += ':' + path
	else:
		os.environ['PYTHONPATH'] = path

if curdir == '.':
	basedir = os.path.dirname(os.getcwd())
else:
	basedir = os.path.dirname(curdir)

console = False

if os.path.isfile(os.path.join(curdir, '__uninstalled__.py')):
	if basedir == '':
		print 'Running sugar from current directory...'
	else:
		print 'Running sugar from ' + basedir + ' ...'
	sys.path.insert(0, basedir)
	append_to_python_path(basedir)
	console = True
else:
	print 'Running the installed sugar...'
	
append_to_python_path(os.path.expanduser('~/.sugar/activities'))

if console:
	print 'Redirecting output to the console, press ctrl+d to open it.'
	
from sugar.session import session

session.start(console)
