#include "nsISupports.idl"

interface nsIWebBrowser;

[scriptable, uuid(475e1194-92bc-4e03-92f3-5ad6ccddaca3)]
interface nsIBrowserHelper : nsISupports
{
  nsIWebBrowser getBrowser(in long id);

  void registerBrowser(in long id, in nsIWebBrowser browser);

  void unregisterBrowser(in long id); 
};
