#!/usr/bin/python

import sys

result = 'colors = [\n'

hex_file = open(sys.argv[1], 'r')

for line in hex_file.readlines():
	[ stroke, fill ] = line.split()
	result += '[\'#%s\', \'#%s\'], \\\n' % (fill, stroke)

result += ']'

hex_file.close()

print result

