# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: sugar ci

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build-fedora:

    runs-on: ubuntu-latest
    container: fedora

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies for OS
        run: dnf install -y autoconf make intltool glib2-devel gtk3-devel gcc
      - name: Install dependencies for python
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install empy
      - name: Run autoconf
        run: ./autogen.sh
      - name: Make
        run: make
      - name: Install
        run: make install
  
  build-ubuntu:

    runs-on: ubuntu-latest
    container: ubuntu 

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install dependencies for OS
        run: |
          apt-get update
          apt-get install -y autoconf make intltool libglib2.0-dev libgtk-3-dev build-essential
      - name: Install dependencies for python
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          pip install empy
      - name: Run autoconf
        run: ./autogen.sh
      - name: Make
        run: make
      - name: Install
        run: make install
